// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller"
application.register("form", FormController)

import NestedController from "./nested_controller"
application.register("nested", NestedController)

import PageController from "./page_controller"
application.register("page", PageController)

import SlimController from "./slim_controller"
application.register("slim", SlimController)
