development:
  adapter: redis
  url: <%= ENV.fetch("RAILS_REDIS_URL") { "redis://localhost:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("RAILS_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: partecipo_production
