production:
  periodic_cleanup:
    class: CleanJob
    queue: background
    args:
      days: ENV.fetch("RAILS_CLEAN_AFTER_DAYS", nil).to_i
    schedule: "0 2 * * *"
  periodic_reminder:
    class: ReminderJob
    queue: background
    schedule: "0 6 * * *"
