title: Partecipo
group: Partecipo Group
header: /head.html
footer: /footer.html
subtitle: Gestione prenotazioni
email: partecipo@partecipo.com
domain: isprambiente.it
restricted_access: false
app:
  url: https://partecipo.com
action_mailer:
  default_url_option: 
    host: 'partecipo.com'
    protocol: 'https'
  smtp_settings:
   address: 'smtp.partecipo.com'
   port: 465
   domain: 'partecipo.com'
   ssl: true
   username: 'partecipo@partecipo.com'
   sender: 'partecipo@partecipo.com'
database_url: 'postgres://myuser:mypass@localhost/somedatabase'
