title: Sel-Int
group: ISPRA
header: https://common.intranet.isprambiente.it/head.html
footer: https://common.intranet.isprambiente.it/footer.html
subtitle: Gestione selezioni interne
email: progressionilivello54@isprambiente.it
user_data_lib: nil_data
domain: isprambiente.it
cas: https://auth.isprambiente.it/cas/
rubrica: https://rubrica.intranet.isprambiente.it/home/dettagli
tracker: piwik.intranet.isprambiente.it
app:
  url: https://prenotazioni.intranet.isprambiente.it
copyright:
  title: ISPRA | AGP-INF - Settore Sviluppo
  link: https://www.isprambiente.it
bug:
  icon: bug
  title: Segnala un problema nel programma
  link: http://intranet.isprambiente.it/giri/selectgroup/group/dir-inf
